"""Add Ops and Telephony tables

Revision ID: 53e518e144d1
Revises: 001_initial_phase4
Create Date: 2026-09-14 02:36:14.111848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e518e144d1'
down_revision: Union[str, None] = '001_initial_phase4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
