@echo off
echo Restarting AirSense FastAPI Backend on Port 8000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8000 ^| findstr LISTENING') do (
    echo Killing process PID %%a on port 8000...
    taskkill /f /pid %%a > nul 2>&1
)
timeout /t 2 /nobreak > nul
echo Starting fresh uvicorn instance...
start /min "AirSense Backend" cmd /c "py -u -m uvicorn apps.api.main:app --host 0.0.0.0 --port 8000"
timeout /t 5 /nobreak > nul
echo Testing local health probe...
py -c "import urllib.request, json; resp = urllib.request.urlopen('http://127.0.0.1:8000/api/v1/health/readiness'); print(json.loads(resp.read().decode()))"
