import os
import json
import pandas as pd
import numpy as np
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error
import joblib
from typing import Optional

class ImpactForecastingModel:
    """
    Multi-Dimensional Operational Intelligence Model.
    Trains on historical weather events, government policy notices, and business impact 
    to forecast future disruption scores and financial loss.
    """
    def __init__(self, base_path: Optional[str] = None):
        if base_path is None:
            if os.path.exists("D:/"):
                base_path = "D:/MUNIM - UOE @BIC/AirSense/data/ops"
            else:
                base_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data", "ops"))
        self.weather_lake = os.path.join(base_path, "weather_lake")
        self.policy_lake = os.path.join(base_path, "policy_lake")
        self.impact_lake = os.path.join(base_path, "impact_lake")
        if os.path.exists("D:/"):
            self.model_path = "D:/MUNIM - UOE @BIC/AirSense/data/models/ops_impact_model.joblib"
        else:
            self.model_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "data", "models", "ops_impact_model.joblib"))
        
        os.makedirs(os.path.dirname(self.model_path), exist_ok=True)
        self.model = None

    def _load_data(self) -> pd.DataFrame:
        data = []
        for filename in os.listdir(self.weather_lake):
            if not filename.endswith('.json'): continue
            
            # Allow skipping unmatched files generated by integration tests
            w_path = os.path.join(self.weather_lake, filename)
            p_path = os.path.join(self.policy_lake, filename)
            i_path = os.path.join(self.impact_lake, filename)
            
            if not (os.path.exists(w_path) and os.path.exists(p_path) and os.path.exists(i_path)):
                continue
            
            with open(w_path, 'r') as f:
                w_data = json.load(f)
            with open(p_path, 'r') as f:
                p_data = json.load(f)
            with open(i_path, 'r') as f:
                i_data = json.load(f)
                
            data.append({
                "pm2_5": w_data["pm2_5"],
                "temperature": w_data["temperature"],
                "lead_time_hours": p_data["extracted_lead_time_hours"],
                "is_closure": 1 if p_data["event_type"] == "Closure" else 0,
                "is_advisory": 1 if p_data["event_type"] == "Advisory" else 0,
                "target_disruption_score": i_data["disruption_score"]
            })
            
        return pd.DataFrame(data)

    def train_model(self):
        print("Loading Data Lake for Multi-Dimensional Training...")
        df = self._load_data()
        
        if len(df) == 0:
            print("No data found to train.")
            return

        X = df[["pm2_5", "temperature", "lead_time_hours", "is_closure", "is_advisory"]]
        y = df["target_disruption_score"]

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        print(f"Training LightGBM Impact Forecaster on {len(X_train)} historical events...")
        self.model = lgb.LGBMRegressor(n_estimators=100, learning_rate=0.05, random_state=42)
        self.model.fit(X_train, y_train)

        preds = self.model.predict(X_test)
        r2 = r2_score(y_test, preds)
        mae = mean_absolute_error(y_test, preds)

        print(f"Model Training Complete. Test R^2: {r2:.4f}, MAE: {mae:.2f}")

        joblib.dump(self.model, self.model_path)
        print(f"Model successfully saved to {self.model_path}")

    def predict_disruption(self, pm2_5: float, temperature: float, lead_time_hours: float, event_type: str) -> float:
        if self.model is None:
            if os.path.exists(self.model_path):
                self.model = joblib.load(self.model_path)
            else:
                raise RuntimeError("Model not trained yet.")
                
        is_closure = 1 if event_type == "Closure" else 0
        is_advisory = 1 if event_type == "Advisory" else 0
        
        features = pd.DataFrame([{
            "pm2_5": pm2_5,
            "temperature": temperature,
            "lead_time_hours": lead_time_hours,
            "is_closure": is_closure,
            "is_advisory": is_advisory
        }])
        
        return float(self.model.predict(features)[0])

if __name__ == "__main__":
    forecaster = ImpactForecastingModel()
    forecaster.train_model()
